// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ncpmxxinhqqwbrgmqsxr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5jcG14eGluaHFxd2JyZ21xc3hyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk4OTgzNDIsImV4cCI6MjA1NTQ3NDM0Mn0.UBMOwHPt-Ufnq0VGXwECczsqeDMho73kEqqoMTSxPGc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);